# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
# Import your libraries:
import pandas as pd
import numpy as  np 

from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function ([documentation](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html)).

In [3]:
# Your code here:
from sklearn import datasets
# dictionary-like object
diabetesDataset = datasets.load_diabetes()
diabetesDataset.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

Let's explore this variable by looking at the different attributes (keys) of `diabetes`. Note that the `load_diabetes` function does not return dataframes. It returns you a Python dictionary.

In [4]:
# Your code here:
diabetesDataset.DESCR

'.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, total serum cholesterol\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, total cholesterol / HDL\n      - s5      ltg, possibly log of serum triglycerides level\n      - s6      glu, blood sugar

#### The next step is to read the description of the dataset. 

Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable. Read the data description carefully to fully understand what each column represents.

*Hint: If your output is ill-formatted by displaying linebreaks as `\n`, it means you are not using the `print` function.*

In [5]:
# Your code here:
print(diabetesDataset.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

#### Based on the data description, answer the following questions:

1. How many attributes are there in the data? What do they mean?

1. What is the relation between `diabetes['data']` and `diabetes['target']`?

1. How many records are there in the data?

In [9]:
# Enter your answer here:

#How many attributes are there in the data? What do they mean? 10 atributos 

#What is the relation between diabetes['data'] and diabetes['target']? las 10 atributos describe la enfermeda progresiva en la columna 11

#How many records are there in the data? 442 filas 

#### Now explore what are contained in the *data* portion as well as the *target* portion of `diabetes`. 

Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). Inspect the shape of `data` and `target`. Confirm they are consistent with the data description.

In [15]:
import json
from urllib.request import urlopen
import pandas as pd
from pandas.io.json import json_normalize
diabetesDataset.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [17]:
# Your code here:
diabetes = pd.DataFrame(diabetesDataset.data, columns=diabetesDataset.feature_names)
target =  pd.DataFrame(diabetesDataset.target)

diabetes.shape, target.shape

((442, 10), (442, 1))

# Challenge 2 - Perform Supervised Learning on the Dataset

The data have already been split to predictor (*data*) and response (*target*) variables. Given this information, we'll apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset.

#### Let's briefly revisit the linear regression formula:

```
y = β0 + β1X1 + β2X2 + ... + βnXn + ϵ
```

...where:

- X1-Xn: data 
- β0: intercept 
- β1-βn: coefficients 
- ϵ: error (cannot explained by model)
- y: target

Also take a look at the `sklearn.linear_model.LinearRegression` [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html).

#### In the cell below, import the `linear_model` class from `sklearn`. 

In [ ]:
# Your code here:


#### Create a new instance of the linear regression model and assign the new instance to the variable `diabetes_model`.

In [18]:
# Your code here:
diabetes_model = LinearRegression()

#### Next, let's split the training and test data.

Define `diabetes_data_train`, `diabetes_target_train`, `diabetes_data_test`, and `diabetes_target_test`. Use the last 20 records for the test data and the rest for the training data.

In [19]:
# Your code here:
X = diabetes
y = target

X_train, X_test, y_train, y_test = train_test_split(
                                        X.values.reshape(-1,10),
                                        y.values.reshape(-1,1),
                                        train_size   = 0.8,
                                        random_state = 40,
                                        shuffle      = True
                                    )


In [29]:
diabte

array([[-0.00551455, -0.04464164,  0.06492964, ...,  0.00072884,
        -0.01811827,  0.03205916],
       [-0.04547248,  0.05068012, -0.02452876, ...,  0.07120998,
         0.0423449 ,  0.01549073],
       [-0.00551455,  0.05068012, -0.01159501, ..., -0.00259226,
         0.0110081 ,  0.06933812],
       ...,
       [ 0.06350368,  0.05068012, -0.00189471, ...,  0.01770335,
        -0.03581673,  0.00306441],
       [-0.08906294, -0.04464164, -0.04177375, ..., -0.03949338,
         0.0011438 , -0.03007245],
       [ 0.04534098,  0.05068012, -0.00836158, ...,  0.03430886,
         0.02993565,  0.02791705]])

Fit the training data and target to `diabetes_model`. Print the *intercept* and *coefficients* of the model.

In [35]:
# Your code here:
diabetes_model.fit(X = X_train, y = y_train)

diabetes_model.intercept_, diabetes_model.coef_, diabetes_model.score(X_train, y_train)


(array([150.81398414]),
 array([[   24.30324094,  -234.27475469,   558.67936806,   303.40471546,
         -1014.82629141,   576.90198157,   167.90312909,   188.26767955,
           866.25383808,    18.32718138]]),
 0.558332186425256)

#### Inspecting the results

From the outputs you should have seen:

- The intercept is a float number.
- The coefficients are an array containing 10 float numbers.

This is the linear regression model fitted to your training dataset.

#### Using your fitted linear regression model, predict the *y* of `diabetes_data_test`.

In [47]:
# Your code here:
predict = diabetes_model.predict(X = X_test)
predict

array([[ 89.94300224],
       [173.60225052],
       [213.38325901],
       [217.89586324],
       [153.97129196],
       [223.80703241],
       [151.39442011],
       [ 84.96873184],
       [176.4351802 ],
       [141.07710952],
       [168.28563228],
       [119.07979157],
       [ 51.69268434],
       [166.79012436],
       [ 70.17606917],
       [185.92247591],
       [152.73286443],
       [145.49476382],
       [ 96.03277405],
       [144.36943482],
       [ 56.17152673],
       [261.24413484],
       [136.78245828],
       [139.42480414],
       [ 68.80836783],
       [192.35445793],
       [141.74624111],
       [114.23601629],
       [179.76428926],
       [ 70.5190996 ],
       [163.44795613],
       [148.47116418],
       [125.02780455],
       [161.23165998],
       [ 94.69871686],
       [ 56.84895479],
       [114.75603801],
       [ 69.11451378],
       [204.87288428],
       [147.98733538],
       [154.45898782],
       [ 70.32100557],
       [165.22998587],
       [150

#### Print your `diabetes_target_test` and compare with the prediction. 

In [43]:
# Your code here:
y_test

array([[ 91.],
       [ 91.],
       [ 52.],
       [310.],
       [259.],
       [317.],
       [197.],
       [158.],
       [ 52.],
       [ 93.],
       [235.],
       [ 68.],
       [ 99.],
       [122.],
       [134.],
       [175.],
       [ 86.],
       [ 88.],
       [137.],
       [302.],
       [ 52.],
       [281.],
       [200.],
       [ 40.],
       [ 83.],
       [ 78.],
       [ 95.],
       [179.],
       [277.],
       [ 92.],
       [206.],
       [150.],
       [135.],
       [178.],
       [ 84.],
       [ 52.],
       [113.],
       [ 75.],
       [249.],
       [ 61.],
       [252.],
       [200.],
       [216.],
       [ 91.],
       [197.],
       [ 97.],
       [ 49.],
       [151.],
       [104.],
       [242.],
       [296.],
       [181.],
       [270.],
       [173.],
       [230.],
       [233.],
       [ 84.],
       [115.],
       [200.],
       [156.],
       [ 66.],
       [ 72.],
       [212.],
       [139.],
       [178.],
       [160.],
       [30

#### Is `diabetes_target_test` exactly the same as the model prediction? Explain.

In [51]:
# Your explanation here:
#los datos predichos no se asemejan a los datos de test ya que el modelo tiene un ajuste de 0.55, donde almenos 55%
#de los datos puede predecir 
 
from sklearn.metrics import mean_squared_error as mse
mse(y_test, predicciones), diabetes_model.score(X_test, y_test)

(4189.68160019527, 0.35116288023728315)

# Bonus Challenge 1 - Hypothesis Testing with `statsmodels`

After generating the linear regression model from the dataset, you probably wonder: then what? What is the statistical way to know if my model is reliable or not?

Good question. We'll discuss that using Scikit-Learn in Challenge 5. But for now, let's use a fool-proof way by using the ([Linear Regression class of StatsModels](https://www.statsmodels.org/dev/regression.html)) which can also conduct linear regression analysis plus much more such as calcuating the F-score of the linear model as well as the standard errors and t-scores for each coefficient. The F-score and t-scores will tell you whether you can trust your linear model.

To understand the statistical meaning of conducting hypothesis testing (e.g. F-test, t-test) for slopes, read [this webpage](https://onlinecourses.science.psu.edu/stat501/node/297/) at your leisure time. We'll give you a brief overview next.

* The F-test of your linear model is to verify whether at least one of your coefficients is significantly different from zero. Translating that into the *null hypothesis* and *alternative hypothesis*, that is:

    ```
    H0 : β1 = β2 = ... = β10 = 0
    HA : At least one βj ≠ 0 (for j = 1, 2, ..., 10)
    ```

* The t-tests on each coefficient is to check whether the confidence interval for the variable contains zero. If the confidence interval contains zero, it means the null hypothesis for that variable is not rejected. In other words, this particular vaiable is not contributing to your linear model and you can remove it from your formula.

Read the documentations of [StatsModels Linear Regression](https://www.statsmodels.org/dev/regression.html) as well as its [`OLS` class](https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.OLS.html) which stands for *ordinary least squares*.

#### In the next cell, analyze `diabetes_data_train` and `diabetes_target_train` with the linear regression model of `statsmodels`. Print the fit summary.

Your output should look like:

![statsmodels regression](../statsmodels.png)

In [ ]:
# Your code here:


#### Interpreting hypothesis testing results

Answer the following questions in the cell below:

1. What is the F-score of your linear model and is the null hypothesis rejected?

1. Does any of the t-tests of the coefficients produce a confidence interval containing zero? What are they?

1. How will you modify your linear reguression model according to the test results above?

In [ ]:
# Your answers here:

# Challenge 3 - Peform Supervised Learning on a Pandas Dataframe

Now that we have dealt with data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [45]:
# Your code here:
auto = pd.read_csv('../auto-mpg.csv')



Look at the first 5 rows using the `head()` function:

In [46]:
# Your code here:
auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [63]:
# Your code here:
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horse_power   392 non-null    float64
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   car_name      398 non-null    object 
dtypes: float64(5), int64(2), object(1)
memory usage: 25.0+ KB


In [57]:
auto.nlargest(5, 'horse_power' )

mpg  cylinders  displacement  horse_power  weight  acceleration  \
116  16.0          8         400.0        230.0    4278           9.5   
8    14.0          8         455.0        225.0    4425          10.0   
13   14.0          8         455.0        225.0    3086          10.0   
95   12.0          8         455.0        225.0    4951          11.0   
6    14.0          8         454.0        220.0    4354           9.0   

     model_year                      car_name  
116          73        \t"pontiac grand prix"  
8            70          \t"pontiac catalina"  
13           70   \t"buick estate wagon (sw)"  
95           73  \t"buick electra 225 custom"  
6            70          \t"chevrolet impala"

In [62]:
auto.weight = auto.weight.astype('float64')

What is the newest model year and the oldest model year?

In [66]:
# Your code here:
auto[(auto.model_year == auto.model_year.min())| (auto.model_year == auto.model_year.max())].model_year.unique()

array([70, 82], dtype=int64)

Check the dataset for missing values and remove all rows containing at least one missing value.

In [69]:
# Your code here:
auto.isna().sum()

mpg             0
cylinders       0
displacement    0
horse_power     6
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [70]:
# Your code here:
auto.dropna(inplace=True)

In [72]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64  
 2   displacement  392 non-null    float64
 3   horse_power   392 non-null    float64
 4   weight        392 non-null    float64
 5   acceleration  392 non-null    float64
 6   model_year    392 non-null    int64  
 7   car_name      392 non-null    object 
dtypes: float64(5), int64(2), object(1)
memory usage: 27.6+ KB


In [73]:
auto.cylinders.value_counts()

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

*Hint: To separate data for training and test, use the `train_test_split` method we used in previous labs.*

In [80]:
# Your code here:
auto.drop(columns='car_name', inplace=True)

In [150]:
# Your code here:
X = auto.drop(columns='mpg')
y = auto.mpg

X_train, X_test, y_train, y_test = train_test_split(
                                        X.values.reshape(-1,6),
                                        y.values.reshape(-1,1),
                                        train_size   = 0.8,
                                        random_state = 0,
                                        shuffle      = True
                                    )

Now we will processed and peform linear regression on this data to predict the mpg for each vehicle. 

#### In the next cell, create an instance of the linear regression model and call it `auto_model`. Fit `auto_model` with your training data.

In [151]:
# Your code here:
auto_model = LinearRegression()
auto_model.fit(X_train, y_train)
auto_model.score(X_train, y_train)

0.8088490656511089

# Challenge 4 - Evaluate the Model

In addition to evaluating your model with F-test and t-test, you can also use the *Coefficient of Determination* (a.k.a. *r squared score*). This method does not simply tell *yes* or *no* about the model fit but instead indicates how much variation can be explained by the model. Based on the r squared score, you can decide whether to improve your model in order to obtain a better fit.

You can learn about the r squared score [here](). Its formula is:

![R Squared](../r-squared.png)

...where:

* yi is an actual data point.
* ŷi is the corresponding data point on the estimated regression line.

By adding the squares of the difference between all yi-ŷi pairs, we have a measure called SSE (*error sum of squares*) which is an application of the r squared score to indicate the extent to which the estimated regression model is different from the actual data. And we attribute that difference to the random error that is unavoidable in the real world. Obviously, we want the SSE value to be as small as possible.

#### In the next cell, compute the predicted *y* based on `X_train` and call it `y_pred`. Then calcualte the r squared score between `y_pred` and `y_train` which indicates how well the estimated regression model fits the training data.

*Hint: r squared score can be calculated using `sklearn.metrics.r2_score` ([documentation](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html)).*

In [152]:
# Your code here:
y_pred = auto_model.predict(X_train)

In [153]:
from sklearn.metrics import r2_score

r2_score(y_train, y_pred)

0.8088490656511089

#### Our next step is to evaluate the model using the test data. 

We would like to ensure that our model is not overfitting the data. This means that our model was made to fit too closely to the training data by being overly complex. If a model is overfitted, it is not generalizable to data outside the training data. In that case, we need to reduce the complexity of the model by removing certain features (variables).

In the cell below, use the model to generate the predicted values for the test data and assign them to `y_test_pred`. Compute the r squared score of the predicted `y_test_pred` and the oberserved `y_test` data.

In [154]:
# Your code here:
y_pred_test = auto_model.predict(X_test)
print(r2_score(y_test, y_pred_test))
print(auto_model.score(X_test, y_test))

0.8088938602131773
0.8088938602131773


#### Explaining the results

The r squared scores of the training data and the test data are pretty close (0.8146 vs 0.7818). This means our model is not overfitted. However, there is still room to improve the model fit. Move on to the next challenge.

# Challenge 5 - Improve the Model Fit

While the most common way to improve the fit of a model is by using [regularization](https://datanice.github.io/machine-learning-101-what-is-regularization-interactive.html), there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [155]:
# Your code here:
X = auto.drop(columns='mpg')
y = auto.mpg

X_train, X_test, y_train, y_test = train_test_split(
                                        X.values.reshape(-1,6),
                                        y.values.reshape(-1,1),
                                        train_size   = 0.9,
                                        random_state = 0,
                                        shuffle      = True
                                    )

Initialize a new linear regression model. Name this model `auto_model09`. Fit the model to the new sample (training) data.

In [156]:
# Your code here:
auto_model09 = LinearRegression()
auto_model09.fit(X_train, y_train)

LinearRegression()

Compute the predicted values and r squared score for our new model and new sample data.

In [157]:
# Your code here:
pred =auto_model09.predict(X_train)
r2_score(y_train,pred )

0.8102752620591411

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [158]:
# Your code here:
pred =auto_model09.predict(X_test)
r2_score(y_test,pred )

0.7971768846093387

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

In [159]:
from sklearn.feature_selection import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [160]:
# Your code here:
selector = RFE(auto_model, n_features_to_select=3 )

Fit the model and print the ranking

In [161]:
# Your code here:
selector = selector.fit(X, y)
selector.ranking_

array([1, 2, 4, 3, 1, 1])

Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [176]:
# Your code here:
X = auto[['cylinders',
          'displacement', 
          'acceleration',
          'model_year']]
y = auto.mpg

X_train, X_test, y_train, y_test = train_test_split(
                                        X.values.reshape(-1,len(X.columns)),
                                        y.values.reshape(-1,1),
                                        train_size   = 0.8,
                                        random_state = 0,
                                        shuffle      = True
                                    )

In [177]:
 X.values.reshape(-1,len(X.columns)), y.values.reshape(-1,1)

(array([[  8. , 307. ,  12. ,  70. ],
        [  8. , 350. ,  11.5,  70. ],
        [  8. , 318. ,  11. ,  70. ],
        ...,
        [  4. , 135. ,  11.6,  82. ],
        [  4. , 120. ,  18.6,  82. ],
        [  4. , 119. ,  19.4,  82. ]]),
 array([[18. ],
        [15. ],
        [18. ],
        [16. ],
        [17. ],
        [15. ],
        [14. ],
        [14. ],
        [14. ],
        [15. ],
        [15. ],
        [14. ],
        [15. ],
        [14. ],
        [24. ],
        [22. ],
        [18. ],
        [21. ],
        [27. ],
        [26. ],
        [25. ],
        [24. ],
        [25. ],
        [26. ],
        [21. ],
        [10. ],
        [10. ],
        [11. ],
        [ 9. ],
        [27. ],
        [28. ],
        [25. ],
        [19. ],
        [16. ],
        [17. ],
        [19. ],
        [18. ],
        [14. ],
        [14. ],
        [14. ],
        [14. ],
        [12. ],
        [13. ],
        [13. ],
        [18. ],
        [22. ],
        [19. ],
     

Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [178]:
# Your code here: 
auto_model_reduced= LinearRegression()
auto_model_reduced.fit(X_train, y_train)

pred_reduced = auto_model_reduced.predict(X_train)

r2_score(y_train, pred_reduced)

0.7383632089042257

#### Conclusion

You may obtain the impression from this lab that without knowing statistical methods in depth, it is difficult to make major progress in machine learning. That is correct. If you are motivated to become a data scientist, statistics is the subject you must be proficient in and there is no shortcut. 

Completing these labs is not likely to make you a data scientist. But you will have a good sense about what are there in machine learning and what are good for you. In your future career, you can choose one of the three tracks:

* Data scientists who need to be proficient in statistical methods.

* Data engineers who need to be good at programming.

* Data integration specialists who are business or content experts but also understand data and programming. This cross-disciplinary track brings together data, technology, and business and will be in high demands in the next decade.